static char* asciiart = "\n"
   "SSSSSSSSSSSSSSS                           tttt                                                                    \n"
   "SS:::::::::::::::S                       ttt:::t                                                                  \n"
  "S:::::SSSSSS::::::S                       t:::::t                                                                  \n"
  "S:::::S     SSSSSSS                       t:::::t                                                                  \n"
  "S:::::S              aaaaaaaaaaaaa  ttttttt:::::ttttttt    uuuuuu    uuuuuu rrrrr   rrrrrrrrr   nnnn  nnnnnnnn     \n"
  "S:::::S              a::::::::::::a t:::::::::::::::::t    u::::u    u::::u r::::rrr:::::::::r  n:::nn::::::::nn   \n"
"   S::::SSSS           aaaaaaaaa:::::at:::::::::::::::::t    u::::u    u::::u r:::::::::::::::::r n::::::::::::::nn  \n"
 "   SS::::::SSSSS               a::::atttttt:::::::tttttt    u::::u    u::::u rr::::::rrrrr::::::rnn:::::::::::::::n \n"
  "    SSS::::::::SS      aaaaaaa:::::a      t:::::t          u::::u    u::::u  r:::::r     r:::::r  n:::::nnnn:::::n \n"
   "      SSSSSS::::S   aa::::::::::::a      t:::::t          u::::u    u::::u  r:::::r     rrrrrrr  n::::n    n::::n \n"
    "          S:::::S a::::aaaa::::::a      t:::::t          u::::u    u::::u  r:::::r              n::::n    n::::n \n"
     "         S:::::Sa::::a    a:::::a      t:::::t    ttttttu:::::uuuu:::::u  r:::::r              n::::n    n::::n \n"
  "SSSSSSS     S:::::Sa::::a    a:::::a      t::::::tttt:::::tu:::::::::::::::uur:::::r              n::::n    n::::n \n"
  "S::::::SSSSSS:::::Sa:::::aaaa::::::a      tt::::::::::::::t u:::::::::::::::ur:::::r              n::::n    n::::n \n"
  "S:::::::::::::::SS  a::::::::::aa:::a       tt:::::::::::tt  uu::::::::uu:::ur:::::r              n::::n    n::::n \n"
   "SSSSSSSSSSSSSSS     aaaaaaaaaa  aaaa         ttttttttttt      uuuuuuuu  uuuurrrrrrr              nnnnnn    nnnnnn \n\n";
static char* asciitail =
"	                XeLL RELOADED - SFoster Based on 1011f9c Commit \n"
"                   RIP Jimmy, you were a good friend, PAS Forever, \n"
"                   SFoster.com.au/Xell \n\n";